load("//tools:oldgen.bzl", "oldgen")
load("//tools:newgen.bzl", "newgen")

newgen(
    name = "new_test",
    #compatible_with = ["//tools:python3"],
)

oldgen(
    name = "old_test",
    #compatible_with = ["//tools:python3"],
)
